### ISSUE TITLE
Nonlinear behavior

### ISSUE THREAD

**Issue by anddudkin** [joksas/badcrossbar#4]
Hi! Maybe you can help or give some advice with applying non linear I-V curve characteristics in inference mode to yours crossbar simulator. I need to compute voltage drop (same as in badcrossbar) and take into account non linear I-V dependence.

**Comment by joksas** [comment]
Hi @anddudkin 👋

Taking into account only nonlinear IV characteristics or only line resistance effects is doable. *Combining* those two things may be unfeasible for large crossbar arrays.

`badcrossbar` just applies Ohm's law and Kirchhoff's current law to compute voltages and currents; due to the linearity of these circuit laws, this just happens to be a linear algebra problem. But even in this ideal, linear case, computations can be quite expensive for large crossbar arrays. Once you introduce nonlinearities, this becomes an exponentially more difficult problem.

If you are going to introduce nonlinearities, I'd recommend coming up with an approximation for line resistance effects. Computing these effects *precisely* when nonlinear IV behavior is present is likely to fail.

🔗 [Our paper on `badcrossbar`](https://doi.org/10.1016/j.softx.2020.100617)
🔗 [Our paper on nonideality-aware training](https://doi.org/10.1002/advs.202105784), whose section 2.4.1 discusses nonlinear IV modelling.
